config/routes.rb
Rails.application.routes.draw do
  resources :prices
  resources :news
  resources :buildings
  resources :materials
  devise_for :users
  resources :constructions
  

  root 'home#index'

end

app/models/news.rb
class News < ActiveRecord::Base
  validates :title, :body, presence:true
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
    redirect_to news_index_url
  end

  # GET /news/new
  def new
    @news = News.new
    render layout: 'admin'
  end

  # GET /news/1/edit
  def edit
    render layout: 'admin'
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_index_url, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_index_url, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :body)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, 'название' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body, 'текст' %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'сохранить' %>
  </div>
<% end %>

app/views/news/edit.html.erb
<% if user_signed_in? %>
  <% if current_user.is_admin %>
  
<h1>Редактировать новость</h1>

<%= render 'form' %>

 
<%= link_to 'Назад', news_index_path %>
<% else %>
  <%= render 'access' %>
<% end %>
<% end %>

app/views/news/index.html.erb
      <div class="container">
        <div class="row whitefone">

<h1>Новости</h1>

 
    <% @news.each do |news| %>
       <em id="datanews"> <%= news.created_at.strftime("%m-%d-%Y") %></em>
       <p id="titlenews"><strong> <%= news.title %></strong></p>
       <p> <%= simple_format news.body %>

        <% if user_signed_in? %>
        <% if current_user.is_admin %>  

        <%= link_to 'Изменить', edit_news_path(news), class: "btn btn-warning btn-sm" %>
        <%= link_to 'Удалить', news, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Удалить безвозвратно?' } %>
    <% end %>
    
     <% end %>
     </p><hr />
            <% end %>

<br>
<% if user_signed_in? %>
        <% if current_user.is_admin %>
<%= link_to 'Добавить новость', new_news_path, class: "btn btn-success btn-sm pull-right" %>
 <% end %>
        <% end %>

            </div>
            </div>

app/views/news/new.html.erb
<% if user_signed_in? %>
        <% if current_user.is_admin %>

<h1>New News</h1>

<%= render 'form' %>

<%= link_to 'Назад', news_index_path %>

<% else %>
  <%= render 'access' %>
<% end %>
  
<% end %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @news.body %>
</p>

<%= link_to 'Back', news_index_path %>