config/routes.rb
Rails.application.routes.draw do
  resources :prices
  resources :news
  resources :buildings
  resources :materials
  devise_for :users
  resources :constructions
  

  root 'home#index'

end

app/models/building.rb
class Building < ActiveRecord::Base
  validates :title, :body, presence: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" } 
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
    render layout: 'admin'
  end

  # GET /buildings/1/edit
  def edit
    render layout: 'admin'
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:title, :body, :image)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building, html: { multipart: true }) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
   <div class="field">
    <%= f.label 'картинка' %><br>
     <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit 'Сохранить' %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<% if user_signed_in? %>
  <% if current_user.is_admin %>

<h1>Editing Building</h1>

<%= render 'form' %>

<%= link_to 'Показать', @building %> |
<%= link_to 'Назад', buildings_path %>
<% else %>
  <%= render 'access' %>
<% end %>
  
<% end %>

app/views/buildings/index.html.erb
<div class="container">
  <div class="row whitefone">
<h1>Недвижимость</h1>

 
    <% @buildings.each do |building| %>
      
        <p><%= building.title %></p>
        <p class="agreen"><%= image_tag building.image.url(:thumb) %>
        <%= link_to truncate(building.body, length: 1000), building %></p>

          <% if user_signed_in? %>
        <% if current_user.is_admin %>

        <%= link_to 'Изменить', edit_building_path(building), class: "btn btn-warning btn-sm" %>
        <%= link_to 'Удалить', building, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Удалить безвозвратно?' } %>
      
    <% end %>
      <% end %>
            <% end %>


<br>

 <% if user_signed_in? %>
        <% if current_user.is_admin %>
<%= link_to 'Добавить статью', new_building_path, class: "btn btn-success btn-sm pull-right" %>

  <% end %>
            <% end %>
</div></div>

app/views/buildings/new.html.erb
<% if user_signed_in? %>
        <% if current_user.is_admin %>

<h1>New Building</h1>

<%= render 'form' %>

<%= link_to 'Назад', buildings_path %>
<% else %>
  <%= render 'access' %>
<% end %>
  
<% end %>

app/views/buildings/show.html.erb
<div class="container">
  <div class="row whitefone">

<p>
 
  <%= @building.title %>
</p>

<p>
<%= image_tag @building.image.url(:medium) %>
  <%= simple_format @building.body %>
</p>
<% if user_signed_in? %>
  <% if current_user.is_admin %>
<%= link_to 'Изменить', edit_building_path(@building), class: "btn btn-warning btn-sm pull-right" %> <span class="pull-right">&nbsp;</span>
<% end %>
<% end %>

<%= link_to 'Назад', buildings_path, class: "btn btn-success btn-sm pull-right" %>
</div>
  </div>