config/routes.rb
Rails.application.routes.draw do
  resources :prices
  resources :news
  resources :buildings
  resources :materials
  devise_for :users
  resources :constructions
  

  root 'home#index'

end

app/models/material.rb
class Material < ActiveRecord::Base
  validates :title, :body, presence: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" } 
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
    render layout: 'admin'
  end

  # GET /materials/1/edit
  def edit
    render layout: 'admin'
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:title, :body, :image)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_for(@material, html: { multipart: true }) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  
  <div class="field">
    <%= f.label 'картинка' %><br>
     <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить' %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<div class="col-md-8 col-md-offset-2">
<div class="row">

<% if user_signed_in? %>
  <% if current_user.is_admin %>

<h1>Editing Material</h1>

<%= render 'form' %>

<%= link_to 'Показать', @material %> |
<%= link_to 'Назад', materials_path %>
<% else %>
  <%= render 'access' %>
<% end %>
  
<% end %>
</div></div>

app/views/materials/index.html.erb
      <div class="container">
        <div class="row whitefone">

<h1> Строительные материалы</h1>

 
    <% @materials.each do |material| %>
      <tr>
        <%= material.title %>
        <%= image_tag material.image.url(:thumb) %>
        <%= link_to truncate(material.body, length: 1000), material %>

         <% if user_signed_in? %>
        <% if current_user.is_admin %>
        <p>
        <%= link_to 'Изменить', edit_material_path(material), class: "btn btn-warning btn-sm" %>
        <%= link_to 'Удалить', material, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Удалить насовсем?' } %>
      </p>
     <% end %>
            <% end %>
   
    <% end %>


<br>
        <% if user_signed_in? %>
        <% if current_user.is_admin %>
<%= link_to 'Добавить статью', new_material_path, class: "btn btn-success btn-sm pull-right" %>
         <% end %>
        <% end %>

            </div>
            </div>

app/views/materials/new.html.erb
<div class="col-md-8 col-md-offset-2">
<div class="row">
<% if user_signed_in? %>
        <% if current_user.is_admin %>

<h1>New Material</h1>

<%= render 'form' %>

<%= link_to 'Назад', materials_path %>

<% else %>
  <%= render 'access' %>
<% end %>
  
<% end %>
</div></div>

app/views/materials/show.html.erb
<div class="container">
  <div class="row whitefone">

<p>

  <%= @material.title %>
</p>

<p>
 <%= image_tag @material.image.url(:medium) %>
  <%= simple_format @material.body %>
</p>

<% if user_signed_in? %>
  <% if current_user.is_admin %>
<%= link_to 'Изменить', edit_material_path(@material), class: "btn btn-warning btn-sm pull-right" %> <span class=" pull-right"> &nbsp; </span>
<% end %>
<% end %>

<%= link_to 'Назад', materials_path, class: "btn btn-success btn-sm pull-right" %>
</div>
  </div>