config/routes.rb
Rails.application.routes.draw do
  resources :prices
  resources :news
  resources :buildings
  resources :materials
  devise_for :users
  resources :constructions
  

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_access.html.erb
<h1>Доступ запрещен</h1>

app/views/application/_footer.html.erb
 <div id="footer">
 <div class="container">
 <h2 style="text-align: center;">Наши заказчики:</h2> 
 <p style="text-align: center;"><a href="http://www.redkuadrate.ru/" title="ООО &quot;Красный квадрат&quot;"><%= image_tag 'redsquare.png' %></a> 

 <img border="0" height="10" src="http://almair.pro/images/space.png" width="10" />

 <img border="0" height="10" src="http://almair.pro/images/space.png" width="10" />

  <a href="http://www.oemz.ru/" title="ОАО &quot;Омский электромеханический завод&quot;">

  <%= image_tag 'omz.png' %>
  </a>

  <br /> <a href="http://www.titan-omsk.ru/" title="Группа компаний &quot;Титан&quot;">
  <img border="0" height="10" src="http://almair.pro/images/space.png" width="10" />

  <%= image_tag 'titan.png' %>
  </a> 

    

  <img border="0" height="10" src="http://almair.pro/images/space.png" width="10" />

  <a href="http://stb-ohrana.ru/" title="Группа компаний &quot;СТБ&quot;">
  <%= image_tag 'stb.png' %>
  </a>



   <a href="https://www.parfum-lider.ru/"> <%= image_tag('parfum.png') %></a>

   <p style="text-align: center;"><span style="color: #838383; font-family: 'Open Sans', sans-serif; font-size: 14px; line-height: 20px; text-align: start;">Строительная компания &quot;РусЭМ&quot;: качественный пиломатериал, деревянные дома, стройка и ремонт, строительная техника в аренду.</span></p> 

 </div>
</div>

app/views/application/_header.html.erb
 
        <div id="main-fixed">
          
        </div>

        <div  class="container">
        <div class="row">
              <div class="col-lg-12">
              <div id="hat">
          <%= image_tag "label.png", title: "label" %>
        </div>
              <div id="htop">
                 <p class="text-center" id="title-rusem">
                Омская Строительная Компания РусЭМ
               </p>
               <p  class="text-right" id="telefax"><span><%= image_tag "zvonki.png" %>Телефон/факс: (3812) 40-69-59</span> <br /> <span><%= image_tag "mail.png" %>Е-mail: sk-rusm@yandex.ru</span> </p>
              </div>
              </div>
          
        </div>
          
        </div>

<div class="container">
  <div class="row">
  <div class="col-lg-1">
    
  </div>


  <div class="col-lg-10 menubar">

    <table>
       
      
        <tr>
          <td><%= link_to 'ГЛАВНАЯ', root_path %></td><td><%= link_to "строительные работы", constructions_path %></td><td><%= link_to 'стройматериалы', materials_path %></td>



          <td>


         
 
                     <!--  <ul class="nav nav-pills">
                      
                      <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            недвижимость <br /> <span class="glyphicon glyphicon-chevron-down"></span>

                        </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "недвижимость", buildings_path %></li>
                          <li><%= link_to "строительные работы", constructions_path %></li>
                        </ul>
                      </li>
                      
                    </ul>
 -->
              <%= link_to "недвижимость", buildings_path %>
          </td>


          <td><%= link_to 'новости', news_index_path %></td><td><%= link_to 'прайс', prices_path, target: '_blank' %></td>

 


          <% if user_signed_in? %>
        <% if current_user.is_admin %>
      <td><%= link_to "Выйти", destroy_user_session_path, method: :delete %></td><% end %> <% end %>
        </tr>
      


    </table>
  </div>

  <div class="col-lg-1">
    
  </div>
    
  </div>
  
</div>